# -*- coding: utf-8 -*-
"""Predictive analysis using LSTM (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lfNFmdnTPnvoW16Zhcbq5H2RrzObyEma
"""

import pandas as pd
import numpy as np

data = pd.read_csv('data_vader.csv')

data.head()

data.info()

data.describe()

data1 = data.drop_duplicates(subset=['Text'])
data1 = data1.reset_index(drop=True)
data1.head()

data1['sentiment_vader'].value_counts()

positive_sample = data1[data1['sentiment_vader'] == 'positive'].sample(n=8000, random_state=42)
negative_sample = data1[data1['sentiment_vader'] == 'negative'].sample(n=8000, random_state=42)
neutral_sample = data1[data1['sentiment_vader'] == 'neutral'].sample(n=8000, random_state=42)

balanced_data = pd.concat([positive_sample, negative_sample, neutral_sample])

balanced_data_vader = balanced_data.sample(frac=1, random_state=42).reset_index(drop=True)
print(balanced_data_vader['sentiment_vader'].value_counts())

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
balanced_data_vader['sentiment_encoded'] = label_encoder.fit_transform(balanced_data_vader['sentiment_vader'])
data['sentiment_encoded'] = label_encoder.fit_transform(data['sentiment_vader'])

balanced_data_vader.head()

from sklearn.model_selection import train_test_split

def data_split(data):
  X_train, X_test, y_train, y_test = train_test_split(data['Text'], data['sentiment_encoded'], test_size=0.2, random_state=42)
  return X_train, X_test, y_train, y_test

train_sentences, test_sentences, train_labels, test_labels = data_split(balanced_data_vader)
print(f'Total data for training : {train_sentences.nunique()}')
print(f'Total data for testing : {test_sentences.nunique()}')
print(f"""Total sentiments counts for train data :
     {train_labels.value_counts()}""")
print(f"""Total sentiments counts for test data :
     {test_labels.value_counts()}""")

import tensorflow
import keras
#from keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

vocab_size = 17000
oov_tok = ''
embedding_dim = 64
max_length = 296
padding_type='post'
trunc_type='post'

tokenizer = Tokenizer(num_words = vocab_size, oov_token=oov_tok)
tokenizer.fit_on_texts(train_sentences)
word_index = tokenizer.word_index

train_sequences = tokenizer.texts_to_sequences(train_sentences)
train_padded = pad_sequences(train_sequences, padding='post', maxlen=max_length)

test_sequences = tokenizer.texts_to_sequences(test_sentences)
test_padded = pad_sequences(test_sequences, padding='post', maxlen=max_length)

from tensorflow.keras import Sequential
from tensorflow.keras import regularizers
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

model = Sequential([
    Embedding(vocab_size+1, embedding_dim, input_length=max_length, embeddings_regularizer = regularizers.l2(0.0005)),
    Bidirectional(LSTM(128, return_sequences=True)),
    BatchNormalization(),
    Dropout(0.5),
    Bidirectional(LSTM(64)),
    BatchNormalization(),
    Dropout(0.5),
    Dense(24, activation='relu', kernel_regularizer = regularizers.l2(0.0005), bias_regularizer = regularizers.l2(0.0005)),
    BatchNormalization(),
    Dropout(0.5),
    Dense(3, activation='softmax', kernel_regularizer=regularizers.l2(0.001),bias_regularizer=regularizers.l2(0.001),)
])

model.compile(loss='sparse_categorical_crossentropy',optimizer='Nadam', metrics=['accuracy'])
model.summary()

callbacks = [
    EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True),
    ModelCheckpoint('best_model.h5', save_best_only=True)
]

history = model.fit(train_padded, train_labels, epochs=15, validation_split=0.2, batch_size=128, callbacks=callbacks)

import matplotlib.pyplot as plt
plt.plot(history.history['loss'], label=' training data')
plt.plot(history.history['val_loss'], label='validation data')
plt.title('Loss for Text Classification')
plt.ylabel('Loss value')
plt.xlabel('No. epoch')
plt.legend(loc="upper left")
plt.show()

plt.plot(history.history['accuracy'], label='training data')
plt.plot(history.history['val_accuracy'], label='validation data')
plt.title('CategoricalAccuracy for Text Classification')
plt.ylabel('CategoricalAccuracy value')
plt.xlabel('No. epoch')
plt.legend(loc="upper left")
plt.show()

from tensorflow.keras.models import load_model

best_model = load_model('best_model.h5')

print("Generate predictions for all samples")
predictions = best_model.predict(test_padded)
print(predictions)
predict_results = predictions.argmax(axis=1)

print(predict_results.shape)
if len(predict_results.shape) == 1:
    y_pred = predict_results
else:
    y_pred = np.argmax(predict_results, axis=1)

print(y_pred)

from sklearn.metrics import accuracy_score
y_test=test_labels
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')

from sklearn.metrics import confusion_matrix,classification_report
import seaborn as sns
cm=confusion_matrix(y_test,y_pred)
ax=sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=label_encoder.classes_, yticklabels=label_encoder.classes_)
ax.set_title('Confusion Matrix')
ax.set_xlabel('y_test')
ax.set_ylabel('y_pred')

print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))